import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./context/**/*.{js,ts,jsx,tsx,mdx}",
    "./hooks/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        luxury: {
          black: "#0c0a09",
          gold: "#b45309",
          goldDark: "#92400e",
          goldLight: "#d97706",
          cream: "#fafaf9",
          darkText: "#1c1917",
          white: "#ffffff",
          success: "#15803d",
          warning: "#b45309",
          danger: "#b91c1c",
          purple: "#7e22ce",
          blue: "#1d4ed8",
          gray: "#a8a29e",
          border: "#d6d3d1",
          borderLight: "#e7e5e4",
        },
        // Legacy tokens remapped to Elegant Luxury
        "error-container": "#fee2e2",
        "primary-fixed-dim": "#fed7aa",
        "on-primary-container": "#fffbeb",
        "on-error-container": "#7f1d1d",
        "inverse-surface": "#0c0a09",
        "on-error": "#ffffff",
        "on-primary-fixed": "#451a03",
        error: "#b91c1c",
        "outline-variant": "#d6d3d1",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffedd5",
        "inverse-primary": "#f59e0b",
        "on-surface-variant": "#57534e",
        background: "#fafaf9",
        "on-secondary-fixed": "#1c1917",
        "on-tertiary-fixed": "#451a03",
        "on-secondary-fixed-variant": "#44403c",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#57534e",
        "surface-container-highest": "#e7e5e4",
        "on-primary": "#ffffff",
        "secondary-container": "#e7e5e4",
        "on-tertiary-container": "#7c2d12",
        "surface-container": "#fafaf9",
        "surface-variant": "#f5f5f4",
        "surface-bright": "#ffffff",
        "on-tertiary-fixed-variant": "#9a3412",
        tertiary: "#b45309",
        "primary-container": "#fef3c7",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#d6d3d1",
        "surface-container-low": "#fafaf9",
        secondary: "#57534e",
        "on-background": "#1c1917",
        "surface-dim": "#e7e5e4",
        "on-surface": "#1c1917",
        "primary-fixed": "#fef3c7",
        outline: "#a8a29e",
        "tertiary-fixed-dim": "#fed7aa",
        "on-primary-fixed-variant": "#92400e",
        surface: "#fafaf9",
        "inverse-on-surface": "#fafaf9",
        "surface-tint": "#b45309",
        primary: "#b45309",
        "tertiary-container": "#ffedd5",
        "secondary-fixed": "#e7e5e4",
        "surface-container-high": "#f5f5f4",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "16px",
        xs: "8px",
        gutter: "24px",
        "margin-desktop": "40px",
        xxl: "80px",
        "margin-mobile": "16px",
        lg: "32px",
        base: "4px",
        xl: "48px",
        md: "24px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        blob: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "33%": { transform: "translate(30px, -50px) scale(1.1)" },
          "66%": { transform: "translate(-20px, 20px) scale(0.9)" },
          "100%": { transform: "translate(0px, 0px) scale(1)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        }
      },
      animation: {
        "fade-in-up": "fade-in-up 0.5s ease-out forwards",
        "blob": "blob 7s infinite",
        "pulse-glow": "pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
export default config;
